# Ejercicio de introducción a Pytorch
Haremos un recorrido por los aspectos fundamentales de pytroch desde el manejo de tensores hasta el entrenamiento y evaluación de una red neuronal. 
Para completarlo podemos consultar
 [ESTE](https://colab.research.google.com/github/phlippe/uvadlc_notebooks/blob/master/docs/tutorial_notebooks/tutorial2/Introduction_to_PyTorch.ipynb#scrollTo=u-L7YQmcHvX8) cuaderno.y otros recursos dados a lo largo del cuaderno.


Primero importamos algunas librerías básicas

In [ ]:
## Standard libraries
import os
import math
import numpy as np 
import time

## Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline 
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

## Progress bar
from tqdm.notebook import tqdm


In [ ]:
#Pytorch libraries
import torch
import torch.nn as nn
import torch.nn.functional as F

import torchvision
import torch.utils.data
import torchvision.transforms as transform

Primero recordemos algunas funconalidades de los tensores.

In [ ]:
t = torch.rand(100,110, 3)
t

tensor([[[0.7754, 0.4108, 0.2801],
         [0.6638, 0.7650, 0.1626],
         [0.8205, 0.5782, 0.2796],
         ...,
         [0.3817, 0.9250, 0.4702],
         [0.9685, 0.6813, 0.3265],
         [0.9791, 0.0249, 0.8259]],

        [[0.0441, 0.8067, 0.9758],
         [0.7250, 0.5733, 0.2441],
         [0.0899, 0.9234, 0.8030],
         ...,
         [0.7261, 0.2068, 0.9898],
         [0.6721, 0.9241, 0.7888],
         [0.2681, 0.6118, 0.6390]],

        [[0.0231, 0.9740, 0.6599],
         [0.4534, 0.2646, 0.8659],
         [0.7886, 0.6700, 0.4394],
         ...,
         [0.2131, 0.3804, 0.5029],
         [0.1915, 0.0651, 0.5762],
         [0.3850, 0.9171, 0.5077]],

        ...,

        [[0.2380, 0.8011, 0.8730],
         [0.1506, 0.9590, 0.3390],
         [0.8569, 0.6297, 0.3851],
         ...,
         [0.4366, 0.9744, 0.9372],
         [0.5358, 0.6469, 0.2084],
         [0.2901, 0.0440, 0.3513]],

        [[0.3574, 0.1125, 0.6978],
         [0.8938, 0.3168, 0.4762],
         [0.

In [ ]:
torch.permute(t, (0,3,2,1))

torch.Size([1, 3, 110, 100])

In [ ]:
# Crear un tensor aleatorio con entradas entre 0 y 1, de tamaño 3x3
primer_tensor = torch.rand(3, 3)

# Crear un tensor de tamaño 3x3 con valores en una distribución normal estandar
segundo_tensor = _______
# Calcular el tamaño de los tensores
tensor_size = primer_tensor.___

# Imprimir los valores de los vectores y su tamaño


tensor([[0.5945, 0.7875, 0.4388],
        [0.7779, 0.3967, 0.8033],
        [0.2927, 0.1533, 0.8901]])
torch.Size([3, 3])


In [ ]:
# Crear una matriz de unos de tamaño 3 by 3
tensor_of_ones = torch.____(3, 3)

# Crear una matrix identidad de tamaño 3 by 3
identity_tensor = torch.____(3)

# Multiplicar las dos matrices anteriores
matrices_multiplied = torch.____
print(matrices_multiplied)

# ¿Qué ocurre si las multiplica usando * ?

### Cálculo de gradientes
Calculemos un gradiente utilizando Pytorch. La función está en la gráfica Graph0.

Para esto, puede ir a la sección Dynamic Computation Graph and Backpropagation, del cuaderno inicial.

In [ ]:
# Initialize x, y and z to values 4, -3 and 5
x = torch.tensor(4., ____)
y = torch.tensor(____., ____)
z = ____

# Set q to sum of x and y, set f to product of q with z
q = ____
f = ____

# Compute the derivatives
f.____

# Print the gradients
print("Gradient of x is: " + str(____))
print("Gradient of y is: " + str(____))
print("Gradient of z is: " + str(____))

Gradient of x is: tensor(5.)
Gradient of y is: tensor(5.)
Gradient of z is: tensor(1.)


Ahora calculemos los gradientes para la función descrita en la imagen Graph1

In [ ]:
# Initializar x,y,z como tensores aleatorios de tamaño (1000,100)
# Multiplicar los tensores x con y
q = ____

# Multiplicar componente a componente los tensores z con q
f = ____

mean_f = torch.mean(f)

# Calcular los gradientes
____

### Construcción de redes neuronales con Pytorch

Construimos una red neuronal en Pytorch de forma *manual*. la entrada serán imágenes de tamaño (28,28). Es decir contienen pixeles de 784 pixeles. 
La red contendrá una capa de entrada, una capa oculta con 200 unidades y una capa de salida con 10 categorías.

In [ ]:
input_layer=torch.rand(784)
# Inicializar los pesos de la red neuronal
weight_1 = torch.rand(__,__)
weight_2 = torch.rand(__,__)

# Multiplicar la capa de entrada con el peso 1
hidden_1 = torch.matmul(__,__)

# Multiplicar la capa oculta con el peso 2
output_layer = ___
print(output_layer)

tensor([10103.1855,  8990.5244, 10255.5020, 11015.8242, 10729.8633,  9323.4658,
         9258.4092, 10563.3281, 10526.0752,  9638.4189])


Ahora construimos la misma rede neuronal pero utilizando los módulos de Pytorch. (Ver sección *The model* del cuaderno)

In [ ]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        # Inicializar las dos capas lineales 
        self.fc1 = nn.Linear(__,__)
        self.fc2 = ___

    def forward(self, x):
      
        # Usar las capas inicializadas y devolver x
        x = self.fc1(x)
        x = self.___
        return x

Construyamos la red neuronal en la gráfica NN1 dada ede forma *manual*



In [ ]:
# Crear tensor aleatorio como capa de entrada
input_layer= ___

# Crear matrices de pesos
weight_1= ___
weight_2= ___
weight_3= ___

# Calcular la primera y segunda capa oculta

hidden_1 = ___
hidden_2 = ___

# Imprimir la salida
print(torch.matmul(__,__))


La anterior era una red neuronal con 2 capas ocultas ocultas en donde no se aplica ninguna función no-lineal. Veamos que ésta se puede construir con una sola capa oculta.

In [ ]:
# Calcular la compuesta de las matrices de pesos
weight_composed_1 = torch.matmul(__,__)
weight = torch.matmul(__,__)

# Multiplicar la capa de entrada por weight e imprimir
print(__)

## Entrenamiendo de una red neuronal para reconocimiento de dígitos (MNIST Dataset)
### Preparar los datos

Para preparar los datos primero creamos un parámetro *transform* para transformarlos. Haremos dos cosas:
- Transformar las imágenes del MNIST Dataset a tensores para poder alimentar la red neuronal. Esto lo hacemos con el método ToTensor.
- Por otro lado, debemos normalizarlos con respecto a una media y variaza. Esto lo hacemos con el método Normalize. En este caso usaremos una media de 0.1307 y varianza de 0.3081. (Tenga en cuenta que en el MNIST Dataset los pixeles son en escala de grises, por lo cual sólo tienen un canal de código de color.)

Para componer ambas transformaciones (Convertir a tensor y normalizar) usamos transforms.Compose ver [AQUÍ](https://www.programcreek.com/python/example/104832/torchvision.transforms.Compose)


In [ ]:
# Transformar los datos a tensores y normalizarlos 
transform = transforms.Compose([transforms.___,
								transforms.Normalize((___), ((___)))])

Ahora definimos el conjunto de entrenamiento y testeo. Torchvision permite cargar datasets conocidos para visión como el MNIST. 
Para entender y completar los parámetros ver [AQUÍ](https://pytorch.org/vision/main/generated/torchvision.datasets.MNIST.html).

In [ ]:
# Preparar el training set y testing set
trainset = torchvision.datasets.MNIST('mnist', train=___, 
									  download=___, transform=___)
testset = ____('mnist',___,___,___)


El método DataLoader hace parte de torch.utils.data y permite cargar los datos por lotes de un tamaño definido. Para entender los parámetros ver [AQUÍ](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader).
Preparar los datos para entrenamiento y testeo de manera que se procesen 32 imágenes cada vez y se barajen cada vez.

In [ ]:
# Preparar training loader y testing loader. 
# Usar los parámetros dataset, batch_size, shuffle y num_workers.
trainloader = torch.utils.data.DataLoader(___, ___, ___, num_workers=0)
testloader = torch.utils.data.DataLoader(___, ___, ___, num_workers=0)

Construya una clase para una red neuronal que será usada para entrenar el MNIST dataset. El dataset contiene imagenes de dimensiones (28,28,2), así que usted deducirá el tamaño de la capa de entrada. Para las calas ocultas use 200 unidades y para la capa de salida 10 unidades (una por cada categoría (Dígitos del 0 al 9)).
Como función de activación use Relu de manera funcional (nn.Functional ya está importado como F).


In [ ]:
# Define the class Net
class Net(nn.Module):
    def __init__(self):    
    	# Define all the parameters of the net
        super(Net, self).__init__()
        self.fc1 = nn.Linear(___, ___)
        self.fc2 = ___

    def forward(self, x):   
    	# Do the forward pass
        x = F.relu(self.__(__))
        x = self.__(__)
        return x

###Entrenamiento del modelo

Por favor analice cuidadosamente el siguiente código, hasta que quede claro los pasos de entrenamiento y evaluación del modelo.

En primer lugar, revisemos si estamos trabajando en GPU. De lo contrario debemos cambiar el tipo de entorno de ejecución en el menú de Colab.

In [ ]:
gpu_avail = torch.cuda.is_available()
print(f"Is the GPU available? {gpu_avail}")

Le daremos nombre a nuestro dispositivo GPU, al cual debemos transferir nuesto modelo y los datos a utilizar.

In [ ]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print("Device", device)

Definimos nuestro modelo

In [ ]:
model=Net()
print(model)

Empujamos nuestro modelo al dispositivo GPU

In [ ]:
# Push model to device. Has to be only done once
model.to(device)

Definimos el ptimizador y la función de costo

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.001) # descenso de gradiente
loss_module = nn.CrossEntropyLoss()  #función de costo

Entrenamos el modelo, siguiendo los 5 pasos vistos en clase

In [ ]:
def train_model(model, optimizer, testloader, loss_module, num_epochs=1):
    # Set model to train mode
    model.train() 
    
    # Training loop
    for epoch in tqdm(range(num_epochs)):
        for data_inputs, data_labels in testloader:
            data_inputs = data_inputs.view(-1, 28 * 28)
            ## Step 1: Move input data to device (only strictly necessary if we use GPU)
            data_inputs = data_inputs.to(device)
            data_labels = data_labels.to(device)

           
            
            ## Step 2: Run the model on the input data
            preds = model(data_inputs)
            preds = preds.squeeze(dim=1) # Output is [Batch size, 1], but we want [Batch size]
            
            ## Step 3: Calculate the loss
            loss = loss_module(preds, data_labels)
            
            ## Step 4: Perform backpropagation
            # Before calculating the gradients, we need to ensure that they are all zero. 
            # The gradients would not be overwritten, but actually added to the existing ones.
            optimizer.zero_grad() 
            # Perform backpropagation
            loss.backward()
            
            ## Step 5: Update the parameters
            optimizer.step()

In [ ]:
train_model(model, optimizer, trainloader, loss_module)

A continuación evaluaremos el desempeño del modelo

In [ ]:
model.eval()
total, correct =0,0
for i, data in enumerate(testloader, 0):
    inputs, labels = data[0].to(device), data[1].to(device)
    
    # Put each image into a vector
    inputs = inputs.view(-1, 784)
    
    # Do the forward pass and get the predictions
    outputs = model(inputs)
    
    _, outputs = torch.max(outputs.data, 1) #mayor valor entre los dígitos.
    total += labels.size(0)
    correct += (outputs == labels).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))